name = "No Vabbe"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3a93d3df527380e7d06294f1372883adf53e751feab585bfe8a5f78d72c4036"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
