name = "No Vabbe"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b8093c06c90a1db102b14016ab7f68f37d66e7faf2e3bdc7daa80eacb6c8598"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
