name = "No Vabbe"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f321e3d44f74597b2638499a657ed6398dc381d2644a740a61fa5f7928c358b0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
