name = "No Vabbe"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdb97c01c1d81b44e43138a68aafa817db69c6a312602f6dcc8fdbbe05be9fc2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
