name = "No Vabbe"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b90b33dada1bb579f31adaa8fedd2351fe09a5e03083008cfae5b79e4cfa6568"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
