name = "No Vabbe"
author = "Soken"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9221ebf0472318cc592926806654c28dae429e690f5b20ff9d0727894d4ff8bf"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
